### ISSUE TITLE
[SI1-PB1] Membuat Registrasi

### ISSUE THREAD

**Issue by naovalm** [naovalm/SI4403-KEL236#1]

**Comment by naovalm** [comment]
Ini PB1 gambar  
![image](https://user-images.githubusercontent.com/115547998/227447874-32e1211b-72c5-4756-9ab0-4fd1a964ecb9.png)

**Comment by StefanusRicardoM** [comment]
masi ada bug

**Comment by naovalm** [comment]
maaf

**Comment by StefanusRicardoM** [comment]
ya dimaapin
